"""
STAGE 5 — Case ID/Session Setup + Original Evidence Repository + Audit Logging

Two functions:
  create_case_session() — call once before uploading any evidence
  store_evidence()      — final stage, moves file to permanent repository

Storage:
  Dev  → local path  data/repository/{case_id}/{evidence_id}/{filename}
  Prod → MinIO object key (see databases/minio_client.py)
         repository_path stores the MinIO key instead of the local path
"""

import os
import shutil
import json
import logging
from pathlib import Path
from typing import Optional
from infrastructure.schemas import Evidence, EvidenceStatus, CaseSession, AuditLogEntry, CustodyLogEntry

logger = logging.getLogger(__name__)

# Base repository directory (local dev). In production this is MinIO.
REPOSITORY_DIR = os.getenv("ARGUS_REPOSITORY_DIR", "data/repository")


def create_case_session(tenant_id: str, created_by: str) -> CaseSession:
    """
    Create a new CaseSession (one per investigation).
    The case_id and timestamp are auto-generated by the schema.
    """
    session = CaseSession(tenant_id=tenant_id, created_by=created_by)
    
    # Write to PostgreSQL database
    try:
        import psycopg2
        from config.settings import settings
        conn = psycopg2.connect(
            host=settings.postgres_host,
            port=settings.postgres_port,
            database=settings.postgres_db,
            user=settings.postgres_user,
            password=settings.postgres_password,
            connect_timeout=3
        )
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO cases (case_id, tenant_id, created_by, status) VALUES (%s, %s, %s, 'open') ON CONFLICT DO NOTHING;",
            (session.case_id, session.tenant_id, session.created_by)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"  [DB WARNING] Failed to persist case session: {e}")
        
    # Write to tenant-scoped structured file logger
    try:
        from infrastructure.audit_logger import get_audit_logger
        tenant_logger = get_audit_logger(tenant_id)
        tenant_logger.info({
            "event": "case_created",
            "timestamp": session.created_at.isoformat() if hasattr(session.created_at, "isoformat") else str(session.created_at),
            "case_id": session.case_id,
            "created_by": session.created_by,
            "detail": {}
        })
    except Exception as e:
        print(f"  [AUDIT LOGGER WARNING] Failed to log case creation: {e}")

    print(f"\n  Case created: {session.case_id}  tenant={tenant_id}  by={created_by}")
    return session


def store_evidence(evidence: Evidence, case: CaseSession) -> Evidence:
    """
    Store both original immutable evidence and encrypted representation in permanent storage.
    Append custody log entries and audit logs. Set status = STORED.

    Dev:
      Original:  data/repository/{case_id}/{evidence_id}/original/{filename}
      Encrypted: data/repository/{case_id}/{evidence_id}/encrypted/{filename}.enc
    Prod:
      Upload original and encrypted files to MinIO buckets.
    """
    raw_path = evidence.raw_file_path or evidence.file_path
    if evidence.status == EvidenceStatus.FAILED or not raw_path or not os.path.exists(raw_path):
        evidence.status = EvidenceStatus.FAILED
        raise RuntimeError("Cannot store evidence: raw evidence file is missing or in FAILED state.")

    repo_base = Path(REPOSITORY_DIR) / case.case_id / evidence.evidence_id
    orig_repo_dir = repo_base / "original"
    enc_repo_dir = repo_base / "encrypted"

    orig_repo_dir.mkdir(parents=True, exist_ok=True)
    orig_dest = str(orig_repo_dir / evidence.filename)

    # ── 1. Store Original Immutable Bytes ───────────────────────
    try:
        shutil.copy2(raw_path, orig_dest)
        evidence.original_repository_path = orig_dest
        evidence.repository_path = orig_dest  # Backward compatibility reference
    except Exception as e:
        evidence.status = EvidenceStatus.FAILED
        raise RuntimeError(f"Durable storage failure for original evidence: {e}") from e

    evidence.custody_log.append(CustodyLogEntry(
        actor="evidence_store",
        action="original_stored",
        notes=f"original_repository_path={orig_dest}",
    ))

    # ── 2. Store Encrypted Representation ────────────────────────
    if evidence.encrypted and evidence.encrypted_file_path and os.path.exists(evidence.encrypted_file_path):
        enc_repo_dir.mkdir(parents=True, exist_ok=True)
        enc_dest = str(enc_repo_dir / f"{evidence.filename}.enc")
        try:
            shutil.copy2(evidence.encrypted_file_path, enc_dest)
            evidence.encrypted_repository_path = enc_dest
        except Exception as e:
            evidence.status = EvidenceStatus.FAILED
            raise RuntimeError(f"Durable storage failure for encrypted representation: {e}") from e

        evidence.custody_log.append(CustodyLogEntry(
            actor="evidence_store",
            action="encrypted_stored",
            notes=f"encrypted_repository_path={enc_dest}",
        ))

    # ── 3. Prod: Upload to MinIO if client is available ────────────
    orig_minio_key = f"{case.tenant_id}/{case.case_id}/{evidence.evidence_id}/original/{evidence.filename}"
    enc_minio_key = f"{case.tenant_id}/{case.case_id}/{evidence.evidence_id}/encrypted/{evidence.filename}.enc"
    try:
        from minio import Minio
        from config.settings import settings
        
        client = Minio(
            settings.minio_endpoint,
            access_key=settings.minio_access_key,
            secret_key=settings.minio_secret_key,
            secure=settings.minio_secure
        )
        client.fput_object(
            bucket_name=getattr(settings, "minio_bucket_original", "argus-evidence"),
            object_name=orig_minio_key,
            file_path=raw_path,
            content_type="application/octet-stream"
        )
        evidence.original_repository_path = orig_minio_key
        evidence.repository_path = orig_minio_key

        if evidence.encrypted and evidence.encrypted_file_path and os.path.exists(evidence.encrypted_file_path):
            client.fput_object(
                bucket_name=settings.minio_bucket_encrypted,
                object_name=enc_minio_key,
                file_path=evidence.encrypted_file_path,
                content_type="application/octet-stream"
            )
            evidence.encrypted_repository_path = enc_minio_key

        print(f"  [5/5] MINIO UPLOADED original={orig_minio_key}")
    except Exception as e:
        print(f"  [MINIO NOTICE] MinIO upload skipped or unconfigured (using local repo paths): {e}")

    # Append general custody log entry
    evidence.custody_log.append(CustodyLogEntry(
        actor="evidence_store",
        action="stored",
        notes=f"original_path={evidence.original_repository_path} encrypted_path={evidence.encrypted_repository_path}",
    ))

    # Append AuditLogEntry
    evidence.audit_log.append(AuditLogEntry(
        event="evidence_stored",
        tenant_id=case.tenant_id,
        detail={
            "original_repository_path":  evidence.original_repository_path,
            "encrypted_repository_path": evidence.encrypted_repository_path,
            "repository_path":           evidence.repository_path,
            "sha256":                    evidence.sha256_hash,
            "case_id":                   case.case_id,
            "evidence_id":               evidence.evidence_id,
        },
    ))

    # ── 4. Write all audit logs to structured file logger ─────────
    try:
        from infrastructure.audit_logger import get_audit_logger
        tenant_logger = get_audit_logger(case.tenant_id)
        for entry in evidence.audit_log:
            tenant_logger.info({
                "event": entry.event,
                "timestamp": entry.timestamp.isoformat() if hasattr(entry.timestamp, "isoformat") else str(entry.timestamp),
                "case_id": case.case_id,
                "evidence_id": evidence.evidence_id,
                "detail": entry.detail or {}
            })
    except Exception as e:
        print(f"  [AUDIT LOGGER WARNING] Failed to write structured audit logs: {e}")

    # ── 5. Clean up temp intake files ─────────────────────────────
    try:
        if os.path.exists(raw_path):
            os.remove(raw_path)
    except OSError:
        pass
    try:
        if evidence.encrypted_file_path and os.path.exists(evidence.encrypted_file_path):
            os.remove(evidence.encrypted_file_path)
    except OSError:
        pass

    # Update metadata with storage paths and timestamp record
    evidence.metadata["original_repository_path"] = evidence.original_repository_path
    evidence.metadata["encrypted_repository_path"] = evidence.encrypted_repository_path
    if evidence.timestamp_record:
        evidence.metadata["timestamp_record"] = evidence.timestamp_record.model_dump(mode="json")

    # ── 6. Write metadata and logs to Postgres ────────────────────
    try:
        import psycopg2
        from config.settings import settings
        conn = psycopg2.connect(
            host=settings.postgres_host,
            port=settings.postgres_port,
            database=settings.postgres_db,
            user=settings.postgres_user,
            password=settings.postgres_password,
            connect_timeout=3
        )
        cur = conn.cursor()
        
        cur.execute(
            """
            INSERT INTO evidence 
              (evidence_id, case_id, filename, uploaded_by, status, sha256_hash, encrypted, rfc3161_timestamp, metadata, repository_path)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (evidence_id) DO NOTHING;
            """,
            (
                evidence.evidence_id,
                evidence.case_id,
                evidence.filename,
                evidence.uploaded_by,
                "stored",
                evidence.sha256_hash,
                evidence.encrypted,
                evidence.rfc3161_timestamp,
                json.dumps(evidence.metadata),
                evidence.repository_path
            )
        )
        
        for entry in evidence.custody_log:
            cur.execute(
                """
                INSERT INTO custody_log (evidence_id, actor, action, timestamp, notes)
                VALUES (%s, %s, %s, %s, %s);
                """,
                (evidence.evidence_id, entry.actor, entry.action, entry.timestamp, entry.notes)
            )
            
        for entry in evidence.audit_log:
            cur.execute(
                """
                INSERT INTO audit_log (case_id, evidence_id, tenant_id, event, timestamp, detail)
                VALUES (%s, %s, %s, %s, %s, %s);
                """,
                (case.case_id, evidence.evidence_id, case.tenant_id, entry.event, entry.timestamp, json.dumps(entry.detail or {}))
            )
            
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"  [DB WARNING] Failed to persist evidence records: {e}")

    evidence.status = EvidenceStatus.STORED
    print(f"  [5/5] STORED     {evidence.filename} -> orig={evidence.original_repository_path} enc={evidence.encrypted_repository_path}")
    return evidence


def get_case_session(tenant_id: str, case_id: str) -> Optional[CaseSession]:
    """
    Retrieves a CaseSession by case_id, enforcing tenant isolation.
    """
    if not tenant_id:
        raise ValueError("tenant_id is required to fetch a case session.")
    if not case_id:
        raise ValueError("case_id is required to fetch a case session.")

    try:
        import psycopg2
        from config.settings import settings
        conn = psycopg2.connect(
            host=settings.postgres_host,
            port=settings.postgres_port,
            database=settings.postgres_db,
            user=settings.postgres_user,
            password=settings.postgres_password,
            connect_timeout=3
        )
        cur = conn.cursor()
        cur.execute(
            "SELECT case_id, tenant_id, created_at, created_by, status FROM cases WHERE case_id = %s AND tenant_id = %s;",
            (case_id, tenant_id)
        )
        row = cur.fetchone()
        conn.close()
        if row:
            return CaseSession(
                case_id=str(row[0]),
                tenant_id=row[1],
                created_at=row[2],
                created_by=row[3],
                status=row[4]
            )
    except Exception as e:
        logger.error("Failed to query case session: %s", e)
    return None


def get_evidence(tenant_id: str, evidence_id: str) -> Optional[Evidence]:
    """
    Retrieves an Evidence record by evidence_id, enforcing tenant isolation.
    """
    if not tenant_id:
        raise ValueError("tenant_id is required to fetch evidence.")
    if not evidence_id:
        raise ValueError("evidence_id is required to fetch evidence.")

    try:
        import psycopg2
        from config.settings import settings
        conn = psycopg2.connect(
            host=settings.postgres_host,
            port=settings.postgres_port,
            database=settings.postgres_db,
            user=settings.postgres_user,
            password=settings.postgres_password,
            connect_timeout=3
        )
        cur = conn.cursor()
        cur.execute(
            """
            SELECT e.evidence_id, e.case_id, e.filename, e.repository_path, e.uploaded_by, e.upload_timestamp, e.status, e.sha256_hash, e.encrypted, e.rfc3161_timestamp, e.metadata
            FROM evidence e
            INNER JOIN cases c ON e.case_id = c.case_id
            WHERE e.evidence_id = %s AND c.tenant_id = %s;
            """,
            (evidence_id, tenant_id)
        )
        row = cur.fetchone()
        conn.close()
        if row:
            return reconstruct_evidence_from_row(row)
    except Exception as e:
        logger.error("Failed to query evidence: %s", e)
    return None


def list_evidence_by_case(tenant_id: str, case_id: str) -> list[Evidence]:
    """
    Lists all Evidence records for a case_id, enforcing tenant isolation.
    """
    if not tenant_id:
        raise ValueError("tenant_id is required to list evidence.")
    if not case_id:
        raise ValueError("case_id is required to list evidence.")

    evidence_list = []
    try:
        import psycopg2
        from config.settings import settings
        conn = psycopg2.connect(
            host=settings.postgres_host,
            port=settings.postgres_port,
            database=settings.postgres_db,
            user=settings.postgres_user,
            password=settings.postgres_password,
            connect_timeout=3
        )
        cur = conn.cursor()
        cur.execute(
            """
            SELECT e.evidence_id, e.case_id, e.filename, e.repository_path, e.uploaded_by, e.upload_timestamp, e.status, e.sha256_hash, e.encrypted, e.rfc3161_timestamp, e.metadata
            FROM evidence e
            INNER JOIN cases c ON e.case_id = c.case_id
            WHERE e.case_id = %s AND c.tenant_id = %s;
            """,
            (case_id, tenant_id)
        )
        rows = cur.fetchall()
        conn.close()
        for row in rows:
            ev = reconstruct_evidence_from_row(row)
            if ev:
                evidence_list.append(ev)
    except Exception as e:
        logger.error("Failed to list evidence by case: %s", e)
    return evidence_list


def reconstruct_evidence_from_row(row: tuple) -> Optional[Evidence]:
    try:
        meta = row[10]
        if isinstance(meta, str):
            meta = json.loads(meta)
        elif meta is None:
            meta = {}
            
        ts_rec = None
        if "timestamp_record" in meta and isinstance(meta["timestamp_record"], dict):
            try:
                from infrastructure.schemas import TimestampRecord
                ts_rec = TimestampRecord(**meta["timestamp_record"])
            except Exception:
                pass

        return Evidence(
            evidence_id=str(row[0]),
            case_id=str(row[1]),
            filename=row[2],
            file_path=row[3] or "",
            uploaded_by=row[4],
            upload_timestamp=row[5],
            status=row[6],
            sha256_hash=row[7],
            encrypted=row[8],
            rfc3161_timestamp=row[9],
            timestamp_record=ts_rec,
            original_file_path=meta.get("original_repository_path") or row[3],
            original_repository_path=meta.get("original_repository_path") or row[3],
            encrypted_repository_path=meta.get("encrypted_repository_path"),
            metadata=meta,
            repository_path=row[3],
        )
    except Exception as e:
        logger.error("Failed to reconstruct evidence from row: %s", e)
        return None
