[pytest]
testpaths = .
norecursedirs = data repository logs scratch .git .pytest_cache
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:pydantic.*:
    ignore::DeprecationWarning:datetime.*:
