# CVE / NVD + CISA KEV lookup
# Used by: Agent 5a (vulnerability correlation)
class CVEClient:
    def lookup_cve(self, cve_id: str) -> dict: ...
    def search_by_product(self, product: str) -> list: ...
    def get_cisa_kev(self) -> list: ...
