# MITRE ATT&CK knowledge base integration
# Used by: Agent 3 (kill-chain traversal), Agent 5a (technique mapping)
class MitreAttackClient:
    def get_technique(self, technique_id: str) -> dict: ...
    def get_tactics(self) -> list: ...
    def build_killchain_graph(self) -> dict: ...
