# STIX/TAXII threat feed client
# Cross-references MULTIPLE threat feeds, checks feed freshness
class StixTaxiiClient:
    def fetch_indicators(self, server_url: str) -> list: ...
    def check_ioc(self, ioc: str) -> dict: ...
