# Crash recovery / checkpointing
# Resumes a case from its last completed stage instead of restarting from scratch
class Checkpointer:
    def save(self, case_id: str, stage: str, state: dict): ...
    def load(self, case_id: str) -> dict: ...
